"""Unsupervised anomaly detection over each patient's escalation
pattern (PR35/E) -- deliberately NOT a predictive risk score.

The original idea for this PR was "predict which patient is at risk of
a future fall/incident." That task needs real outcome labels (did this
patient actually fall, later, in reality) to train or validate against,
and no such labels exist or can be honestly fabricated for a prototype
with only synthetic demo data. Training a model on synthetic
ground-truth generated by a rule-based simulator would only teach the
model to re-derive that same rule with noise added -- it cannot
discover a real predictive relationship that was never in the data to
begin with, and calling that "ML" would be misleading regardless of
which algorithm sits inside it.

This module solves a different, honestly answerable question instead:
"is this patient's *current* escalation pattern statistically unusual
compared to every other patient the system has seen?" That's
unsupervised anomaly detection -- it needs no outcome labels, only the
distribution of already-real operational data this system generates on
its own (nurse_escalations rows), so it stays true "ML" (scikit-learn's
IsolationForest, not a hand-written threshold) without pretending to
predict a clinical outcome nothing in this codebase could ever validate.

Small-sample caveat: with only a handful of patients (demo/seed-scale
data), "statistically unusual compared to everyone else" is a weak
signal almost by definition -- MIN_PATIENTS_FOR_ANALYSIS below refuses
to even attempt it below a sample size where the comparison would be
close to meaningless, returning an explicit empty result rather than a
number dressed up to look more confident than it is.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime

from backend.db import repositories

MIN_PATIENTS_FOR_ANALYSIS = 5

PRIORITY_SCORES: dict[str, float] = {"LOW": 1.0, "MEDIUM": 2.0, "HIGH": 3.0, "URGENT": 4.0}


def _parse_iso(value: "datetime | str | None") -> datetime | None:
    if value is None:
        return None
    if isinstance(value, datetime):
        return value
    try:
        return datetime.fromisoformat(value)
    except ValueError:
        return None


@dataclass(frozen=True)
class PatientEscalationFeatures:
    patient_id: str
    escalation_count: int
    urgent_count: int
    avg_priority_score: float
    avg_time_to_ack_seconds: "float | None"


@dataclass(frozen=True)
class AnomalyResult:
    patient_id: str
    is_anomalous: bool
    anomaly_score: float
    features: PatientEscalationFeatures


def compute_patient_features(escalations: list) -> list[PatientEscalationFeatures]:
    """Groups raw nurse_escalations rows by patient_id and derives a
    small, fixed feature vector per patient. Rows with no patient_id
    (shouldn't normally happen, but nothing currently enforces it at the
    DB level) are excluded -- there is no patient to compare against
    others for."""
    by_patient: dict[str, list[dict]] = {}
    for e in escalations:
        patient_id = e.get("patient_id")
        if not patient_id:
            continue
        by_patient.setdefault(patient_id, []).append(e)

    features = []
    for patient_id, rows in by_patient.items():
        priority_scores = [PRIORITY_SCORES.get(r["priority"] or "", 0.0) for r in rows]
        ack_durations = []
        for r in rows:
            created = _parse_iso(r.get("created_at"))
            acked = _parse_iso(r.get("acknowledged_at"))
            if created is not None and acked is not None:
                ack_durations.append((acked - created).total_seconds())

        features.append(
            PatientEscalationFeatures(
                patient_id=patient_id,
                escalation_count=len(rows),
                urgent_count=sum(1 for r in rows if r["priority"] == "URGENT"),
                avg_priority_score=sum(priority_scores) / len(priority_scores) if priority_scores else 0.0,
                avg_time_to_ack_seconds=(
                    sum(ack_durations) / len(ack_durations) if ack_durations else None
                ),
            )
        )
    return features


def detect_anomalies(features: list[PatientEscalationFeatures]) -> list[AnomalyResult]:
    """Fits one IsolationForest across all patients' feature vectors and
    scores each patient against that fitted model. Returns [] (not an
    error) if there are fewer than MIN_PATIENTS_FOR_ANALYSIS patients --
    see this module's docstring for why a comparison against too few
    other patients isn't worth presenting as a finding.

    `random_state` is fixed so this function is deterministic given the
    same input -- important both for tests and so a nurse looking at
    this twice in a row without new data doesn't see the flagged
    patient change for no reason.
    """
    if len(features) < MIN_PATIENTS_FOR_ANALYSIS:
        return []

    from sklearn.ensemble import IsolationForest
    from sklearn.preprocessing import StandardScaler

    matrix = [
        [
            f.escalation_count,
            f.urgent_count,
            f.avg_priority_score,
            f.avg_time_to_ack_seconds if f.avg_time_to_ack_seconds is not None else 0.0,
        ]
        for f in features
    ]

    # Standardize before fitting -- without this, avg_time_to_ack_seconds
    # (typically in the hundreds/thousands) dwarfs the other three
    # features (all single-digit), which skews IsolationForest's random
    # split budget toward that one feature and effectively makes this
    # "detect patients with unusually long ack times" rather than a
    # genuinely multi-feature anomaly signal. Each feature is scaled to
    # zero mean / unit variance across the current patient population
    # before the forest ever sees it.
    scaled_matrix = StandardScaler().fit_transform(matrix)

    model = IsolationForest(contamination="auto", random_state=42)
    predictions = model.fit_predict(scaled_matrix)
    scores = model.score_samples(scaled_matrix)

    return [
        AnomalyResult(
            patient_id=f.patient_id,
            is_anomalous=bool(pred == -1),
            anomaly_score=float(score),
            features=f,
        )
        for f, pred, score in zip(features, predictions, scores)
    ]


def analyze() -> dict:
    """GET /analytics/escalation-anomalies backing function. Always
    succeeds (never raises for "not enough data" -- that's communicated
    through total_patients_analyzed / min_patients_required in the
    response instead, so the API contract stays simple for callers)."""
    escalations = repositories.list_nurse_escalations()
    features = compute_patient_features(escalations)
    results = detect_anomalies(features)

    return {
        "total_patients_analyzed": len(features),
        "min_patients_required": MIN_PATIENTS_FOR_ANALYSIS,
        "anomalous_patients": [
            {
                "patient_id": r.patient_id,
                "anomaly_score": round(r.anomaly_score, 4),
                "escalation_count": r.features.escalation_count,
                "urgent_count": r.features.urgent_count,
                "avg_priority_score": round(r.features.avg_priority_score, 2),
                "avg_time_to_ack_seconds": (
                    round(r.features.avg_time_to_ack_seconds, 1)
                    if r.features.avg_time_to_ack_seconds is not None
                    else None
                ),
            }
            for r in results
            if r.is_anomalous
        ],
    }
