"""Delete all demo data generated by seed_demo_data.py (PR12).

Dev/demo tool only, never run automatically. This is a full wipe of
care_requests / robot_tasks / kit_verifications / task_state_transitions /
robot_events -- there is no column marking which rows came from
seed_demo_data.py versus real usage, so this is only appropriate against a
local/demo database. Never point DATABASE_URL at a database you care about
when running this.

Safety: refuses to run if a task is currently active on the default robot,
same guard seed_demo_data.py uses, so it never wipes out a real
in-progress task. Also requires typing "yes" at a confirmation prompt
unless --yes is passed.

Usage:
    python -m backend.scripts.reset_demo_data
    python -m backend.scripts.reset_demo_data --yes
"""
import argparse

from backend.db import repositories
from backend.services import workflow_service


def _check_robot_is_free() -> None:
    active = repositories.get_active_task_for_robot(workflow_service.DEFAULT_ROBOT_ID)
    if active is not None:
        raise RuntimeError(
            "A task is currently active on the default robot -- refusing to wipe "
            "data that includes a real in-progress task. Finish, cancel, or reset "
            "it first."
        )


def reset() -> None:
    _check_robot_is_free()
    repositories.delete_all_data()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--yes", action="store_true", help="Skip the confirmation prompt")
    args = parser.parse_args()

    if not args.yes:
        answer = input(
            "This will permanently delete ALL care_requests / robot_tasks / "
            "kit_verifications / task_state_transitions / robot_events rows. "
            "Type 'yes' to continue: "
        )
        if answer.strip().lower() != "yes":
            print("Aborted -- no changes made.")
            return

    reset()
    print("All data cleared.")


if __name__ == "__main__":
    main()
