apiVersion: 1

datasources:
  - name: PreCareBot Postgres
    uid: precare-postgres
    type: postgres
    access: proxy
    url: db:5432
    database: precare
    user: precare
    isDefault: true
    editable: false
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: precare
