"""PR22: rounding session, patient interaction, nurse escalation tables

Revision ID: 71a902b00d13
Revises: 4a6da14949bf
Create Date: 2026-07-09 19:53:22.919202

Hand-edited after autogenerate (same reason as PR15,
4a6da14949bf_pr15_datetime_timestamps_fks_active_.py): SQLite cannot
ALTER TABLE ... ADD CONSTRAINT on an existing table outside of batch
mode, so adding the `care_requests.rounding_session_id` foreign key is
wrapped in `op.batch_alter_table(...)`. The autogenerated anonymous FK
name (`None`) is also replaced with an explicit name, matching the
`fk_<table>_<column>_<ref_table>` convention used in PR15.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a902b00d13'
down_revision: Union[str, Sequence[str], None] = '4a6da14949bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rounding_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('robot_id', sa.String(), nullable=False),
    sa.Column('room', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('interaction_summary', sa.Text(), nullable=True),
    sa.Column('detected_need', sa.String(), nullable=True),
    sa.Column('escalation_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rounding_sessions_robot_id', 'rounding_sessions', ['robot_id'], unique=False)
    op.create_table('patient_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rounding_session_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('patient_response', sa.Text(), nullable=True),
    sa.Column('input_mode', sa.String(), nullable=False),
    sa.Column('detected_need', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rounding_session_id'], ['rounding_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patient_interactions_rounding_session_id', 'patient_interactions', ['rounding_session_id'], unique=False)
    op.create_table('nurse_escalations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rounding_session_id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['care_requests.id'], ),
    sa.ForeignKeyConstraint(['rounding_session_id'], ['rounding_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nurse_escalations_rounding_session_id', 'nurse_escalations', ['rounding_session_id'], unique=False)
    op.create_index('ix_nurse_escalations_status', 'nurse_escalations', ['status'], unique=False)
    with op.batch_alter_table('care_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rounding_session_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(
            'fk_care_requests_rounding_session_id_rounding_sessions',
            'rounding_sessions', ['rounding_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('care_requests', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_care_requests_rounding_session_id_rounding_sessions', type_='foreignkey')
        batch_op.drop_column('rounding_session_id')
        batch_op.drop_column('source')
    op.drop_index('ix_nurse_escalations_status', table_name='nurse_escalations')
    op.drop_index('ix_nurse_escalations_rounding_session_id', table_name='nurse_escalations')
    op.drop_table('nurse_escalations')
    op.drop_index('ix_patient_interactions_rounding_session_id', table_name='patient_interactions')
    op.drop_table('patient_interactions')
    op.drop_index('ix_rounding_sessions_robot_id', table_name='rounding_sessions')
    op.drop_table('rounding_sessions')
    # ### end Alembic commands ###
