"""initial care_requests and robot_events
 
Revision ID: fa116680c547
Revises: 
Create Date: 2026-07-08 21:37:52.067537
 
"""
from typing import Sequence, Union
 
from alembic import op
import sqlalchemy as sa
 
 
# revision identifiers, used by Alembic.
revision: str = 'fa116680c547'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
 
 
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_requests',
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=True),
    sa.Column('request_label', sa.String(), nullable=True),
    sa.Column('kit', sa.String(), nullable=True),
    sa.Column('risk', sa.String(), nullable=True),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('robot_state', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('robot_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('request', sa.String(), nullable=True),
    sa.Column('kit', sa.String(), nullable=True),
    sa.Column('previous_state', sa.String(), nullable=True),
    sa.Column('next_state', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
 
 
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('robot_events')
    op.drop_table('care_requests')
    # ### end Alembic commands ###
 
